services:
  db:
    image: postgres:16
    restart: unless-stopped
    environment:
      POSTGRES_USER: sywinery
      POSTGRES_PASSWORD: sywinery
      POSTGRES_DB: sywinery
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
volumes:
  pgdata:
